server {
    listen 4200;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/auth/ {
        proxy_pass http://nginx_gateway:80/auth/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/veicoli/ {
        proxy_pass http://nginx_gateway:80/veicoli/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/polizze/ {
        proxy_pass http://nginx_gateway:80/polizze/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/sinistri/ {
        proxy_pass http://nginx_gateway:80/sinistri/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/periti/ {
        proxy_pass http://nginx_gateway:80/periti/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/assicurazione/ {
        proxy_pass http://nginx_gateway:80/assicurazione/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}